name: "Restart Kubectl"
description: "Restart a deployment"
inputs:
  namespace:
    description: "Namespace"
    required: true
  deployment:
    description: "Name of deployment"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      shell: bash
    - run: |
        kubectl -n ${{ inputs.namespace }} rollout restart deployment/${{ inputs.deployment }}
      shell: bash
